import {CONTACT_NOTICE,CONTACT_CONSENT,CONTACT_METHODS,CONTACT_LIMITS,emptyRequest,changeRequest,requestErrors,reviewRequest,escapeHTML as esc} from './contact-model.mjs?v=20260925-1';

// Internal review build: deliberately no receiver, persistence or answer download.
// Do not add survey response IDs, query-string values or shared answer state.
let request=emptyRequest();
const main=document.querySelector('#main');
const required='<span class="required-label">(required)</span>';
const optional='<span class="required-label">(optional)</span>';
const tel='<a href="tel:+61882699333">(08) 8269 9333</a>';
function focusStart(){main.querySelector('h1')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function privacyHTML(){return `<section class="contact-privacy" aria-labelledby="contact-privacy-title"><h2 id="contact-privacy-title">Your information</h2><div class="notice-grid">${CONTACT_NOTICE.map(([title,text])=>`<p><strong>${esc(title)}</strong>${esc(text)}</p>`).join('')}</div><p>Contact Lutheran Care on ${tel} or <a href="mailto:feedback@lutherancare.org.au">feedback@lutherancare.org.au</a>. Read our <a href="https://www.lutherancare.org.au/privacy-policy/" target="_blank" rel="noopener noreferrer">Privacy Policy</a> for access, correction and complaints information.</p></section>`;}
function footerHTML(){return `<div class="contact-footer"><p ${request.age_band==='under_15'?'hidden':''}>If you need help with this form, or cannot safely receive a call or text, call Lutheran Care on ${tel} and ask for the NT Defence Family Support Program.</p><p>This form is not for urgent help. In an emergency in Australia, call 000.</p></div>`;}
function textField(key,label,{hint='',multiline=false}={}){return `<div class="question-group"><label class="field-label" for="${key}">${esc(label)}${['preferred_name','phone'].includes(key)?required:optional}</label>${hint?`<p class="field-hint" id="${key}-hint">${esc(hint)}</p>`:''}${multiline?`<textarea id="${key}" name="${key}" class="textarea" rows="4" maxlength="${CONTACT_LIMITS[key]}" aria-describedby="${key}-hint">${esc(request[key])}</textarea>`:`<input id="${key}" name="${key}" class="text-input" type="${key==='phone'?'tel':'text'}" ${key==='phone'?'inputmode="tel"':''} autocomplete="${key==='preferred_name'?'given-name':key==='phone'?'tel':'off'}" maxlength="${CONTACT_LIMITS[key]}" value="${esc(request[key])}" aria-describedby="${hint?key+'-hint ':''}${key}-error" ${['preferred_name','phone'].includes(key)?'required':''}>`}<p class="contact-field-error" id="${key}-error" ${['preferred_name','phone'].includes(key)?'':'hidden'}></p></div>`;}
function renderForm(){
  main.innerHTML=`<section class="contact-intro"><h1 tabindex="-1">Arrange a conversation</h1><p>Would you like to talk with Lutheran Care about your experience of Defence family life and what support would help? Leave a safe way to contact you.</p></section><form id="contact-form" class="contact-form" novalidate>
  <fieldset class="question-group"><legend>Your age group ${required}</legend><div class="contact-choices">${[['15_plus','15 or older'],['under_15','Under 15']].map(([id,label])=>`<label class="choice"><input type="radio" name="age_band" value="${id}" ${request.age_band===id?'checked':''}><span class="choice-label">${label}</span></label>`).join('')}</div></fieldset>
  <section id="assisted-contact" class="contact-assisted" ${request.age_band==='under_15'?'':'hidden'}><h2>Speak with us first</h2><p>Call Lutheran Care on ${tel} and ask for the NT Defence Family Support Program, or speak with the worker who invited you. They can explain how you can take part and help arrange a conversation.</p><p>You can ask someone you trust to help you.</p></section>
  <div id="contact-fields" ${request.age_band==='15_plus'?'':'hidden'}>
  <div class="contact-pair">${textField('preferred_name','What would you like us to call you?')}${textField('phone','Phone number',{hint:'Include the country code if you are outside Australia.'})}</div>
  <fieldset class="question-group"><legend>How can we safely contact you? ${required}</legend><div class="contact-choices">${Object.entries(CONTACT_METHODS).map(([id,label])=>`<label class="choice"><input type="radio" name="contact_method" value="${id}" ${request.contact_method===id?'checked':''}><span class="choice-label">${esc(label)}</span></label>`).join('')}</div><div id="voicemail-wrap" class="voicemail-choice" ${request.contact_method==='call'?'':'hidden'}><label class="contact-check"><input type="checkbox" name="voicemail" ${request.voicemail?'checked':''}><span>You may leave a voicemail saying Lutheran Care called.</span></label></div></fieldset>
  ${textField('contact_notes','Any times to avoid or other contact instructions?',{hint:'For times, please include your time zone if you are outside the NT.'})}
  ${textField('topic','What would you like to talk about?',{hint:'Please save sensitive details for the conversation and leave out other people’s names.',multiline:true})}
  ${privacyHTML()}<label class="contact-check"><input type="checkbox" name="consent" ${request.consent?'checked':''}><span>${esc(CONTACT_CONSENT)} ${required}</span></label>
  <div class="contact-actions"><button class="text-button" id="clear-details" type="button">Clear details</button><button class="button primary" type="submit" disabled>Review details</button></div></div></form>${footerHTML()}`;
  const form=main.querySelector('#contact-form');const touched=new Set();
  const update=()=>{main.querySelector('#contact-fields').hidden=request.age_band!=='15_plus';main.querySelector('#assisted-contact').hidden=request.age_band!=='under_15';main.querySelector('#voicemail-wrap').hidden=request.contact_method!=='call';form.querySelector('[name="voicemail"]').checked=request.voicemail;form.querySelector('[type="submit"]').disabled=Object.keys(requestErrors(request)).length>0;};
  const save=e=>{const input=e.target;if(!input.name)return;request=changeRequest(request,input.name,input.type==='checkbox'?input.checked:input.value);if(input.name==='age_band'){renderForm();main.querySelector(`[name="age_band"][value="${request.age_band}"]`)?.focus();return;}update();if(input.name==='phone'||input.name==='preferred_name'){const error=main.querySelector(`#${input.name}-error`);if(touched.has(input.name))showError(input.name);}};
  form.addEventListener('input',e=>{if(['text','tel','textarea'].includes(e.target.type))save(e);});
  form.addEventListener('change',e=>{if(['radio','checkbox'].includes(e.target.type))save(e);});
  form.addEventListener('focusout',e=>{if(['phone','preferred_name'].includes(e.target.name)){touched.add(e.target.name);showError(e.target.name);}});
  form.addEventListener('submit',e=>{e.preventDefault();if(Object.keys(requestErrors(request)).length)return;request={...request,...reviewRequest(request)};renderReview();});
  main.querySelector('#clear-details').onclick=()=>{request=emptyRequest();renderForm();focusStart();};update();
}
function showError(key){const input=main.querySelector(`[name="${key}"]`),el=main.querySelector(`#${key}-error`),message=requestErrors(request)[key];el.textContent=message||'';el.hidden=false;input.setAttribute('aria-invalid',message?'true':'false');}
function renderReview(){
  const details=reviewRequest(request);
  const rows=[['Name to use',details.preferred_name],['Phone number',details.phone],['First contact',CONTACT_METHODS[details.contact_method]],...(details.contact_method==='call'?[['Voicemail',details.voicemail?'May leave a voicemail saying Lutheran Care called':'Do not leave a voicemail']]:[]),['Contact instructions',details.contact_notes||'Not provided'],['What you would like to talk about',details.topic||'Not provided']];
  main.innerHTML=`<section class="contact-review"><h1 tabindex="-1">Check your contact details</h1><dl>${rows.map(([label,value])=>`<dt>${esc(label)}</dt><dd>${esc(value)}</dd>`).join('')}</dl><div class="contact-actions"><button class="back-button" id="edit-details" type="button">Change details</button><button class="button primary" id="finish-contact" type="button">Finish</button></div></section>${footerHTML()}`;
  main.querySelector('#edit-details').onclick=()=>{renderForm();focusStart();};main.querySelector('#finish-contact').onclick=renderFinish;focusStart();
}
function renderFinish(){main.innerHTML=`<section class="finish"><h1 tabindex="-1">Thank you for your time</h1><div class="finish-actions"><button class="button secondary" id="review-details">Review my details</button><button class="text-button" id="finish-clear">Clear my details</button></div></section>`;main.querySelector('#review-details').onclick=renderReview;main.querySelector('#finish-clear').onclick=()=>{request=emptyRequest();renderForm();focusStart();};focusStart();}
window.addEventListener('pagehide',()=>{request=emptyRequest();main.replaceChildren();});
window.addEventListener('pageshow',e=>{if(e.persisted){request=emptyRequest();renderForm();}});
renderForm();
