/* Greater Darwin survey location catalogue. See GEOGRAPHY_SOURCES.md. */
'use strict';

window.SURVEY_GEOGRAPHY = Object.freeze({
  version: '2026-09-27-two-level',
  areas: Object.freeze([
    Object.freeze({id:'darwin',label:'Darwin'}),
    Object.freeze({id:'palmerston',label:'Palmerston'}),
    Object.freeze({id:'litchfield',label:'Litchfield'}),
    Object.freeze({id:'greater_darwin_other',label:'Other Greater Darwin area'}),
    Object.freeze({id:'outside',label:'Outside Greater Darwin'}),
    Object.freeze({id:'prefer',label:'Prefer not to say'})
  ]),
  localities: Object.freeze([
    Object.freeze({"id": "acacia_hills", "label": "Acacia Hills", "region": "litchfield"}),
    Object.freeze({"id": "alawa", "label": "Alawa", "region": "darwin"}),
    Object.freeze({"id": "anula", "label": "Anula", "region": "darwin"}),
    Object.freeze({"id": "archer", "label": "Archer", "region": "palmerston"}),
    Object.freeze({"id": "bakewell", "label": "Bakewell", "region": "palmerston"}),
    Object.freeze({"id": "bayview", "label": "Bayview", "region": "darwin"}),
    Object.freeze({"id": "bees_creek", "label": "Bees Creek", "region": "litchfield"}),
    Object.freeze({"id": "bellamack", "label": "Bellamack", "region": "palmerston"}),
    Object.freeze({"id": "berrimah", "label": "Berrimah", "region": "darwin", "aliases": Object.freeze(["Northcrest"])}),
    Object.freeze({"id": "berry_springs", "label": "Berry Springs", "region": "litchfield"}),
    Object.freeze({"id": "black_jungle", "label": "Black Jungle", "region": "litchfield"}),
    Object.freeze({"id": "blackmore", "label": "Blackmore", "region": "litchfield"}),
    Object.freeze({"id": "brinkin", "label": "Brinkin", "region": "darwin"}),
    Object.freeze({"id": "buffalo_creek", "label": "Buffalo Creek", "region": "darwin"}),
    Object.freeze({"id": "casuarina", "label": "Casuarina", "region": "darwin"}),
    Object.freeze({"id": "channel_island", "label": "Channel Island", "region": "litchfield"}),
    Object.freeze({"id": "charles_darwin", "label": "Charles Darwin", "region": "darwin"}),
    Object.freeze({"id": "coconut_grove", "label": "Coconut Grove", "region": "darwin"}),
    Object.freeze({"id": "coolalinga", "label": "Coolalinga", "region": "litchfield"}),
    Object.freeze({"id": "coonawarra", "label": "Coonawarra", "region": "darwin"}),
    Object.freeze({"id": "daly", "label": "Daly", "region": "litchfield"}),
    Object.freeze({"id": "darwin_city", "label": "Darwin City", "region": "darwin", "aliases": Object.freeze(["Darwin CBD", "CBD"])}),
    Object.freeze({"id": "darwin_river", "label": "Darwin River", "region": "litchfield"}),
    Object.freeze({"id": "driver", "label": "Driver", "region": "palmerston"}),
    Object.freeze({"id": "durack", "label": "Durack", "region": "palmerston"}),
    Object.freeze({"id": "east_arm", "label": "East Arm", "region": "greater_darwin_other"}),
    Object.freeze({"id": "east_point", "label": "East Point", "region": "darwin"}),
    Object.freeze({"id": "eaton", "label": "Eaton", "region": "darwin"}),
    Object.freeze({"id": "elrundie", "label": "Elrundie", "region": "palmerston"}),
    Object.freeze({"id": "fannie_bay", "label": "Fannie Bay", "region": "darwin"}),
    Object.freeze({"id": "farrar", "label": "Farrar", "region": "palmerston"}),
    Object.freeze({"id": "fly_creek", "label": "Fly Creek", "region": "litchfield"}),
    Object.freeze({"id": "freds_pass", "label": "Freds Pass", "region": "litchfield"}),
    Object.freeze({"id": "girraween", "label": "Girraween", "region": "litchfield"}),
    Object.freeze({"id": "glyde_point", "label": "Glyde Point", "region": "litchfield"}),
    Object.freeze({"id": "gray", "label": "Gray", "region": "palmerston"}),
    Object.freeze({"id": "gunn", "label": "Gunn", "region": "palmerston"}),
    Object.freeze({"id": "gunn_point", "label": "Gunn Point", "region": "litchfield"}),
    Object.freeze({"id": "herbert", "label": "Herbert", "region": "litchfield"}),
    Object.freeze({"id": "hidden_valley", "label": "Hidden Valley", "region": "darwin"}),
    Object.freeze({"id": "holmes", "label": "Holmes", "region": "darwin"}),
    Object.freeze({"id": "holtze", "label": "Holtze", "region": "litchfield", "aliases": Object.freeze(["Robertson Barracks"])}),
    Object.freeze({"id": "howard_springs", "label": "Howard Springs", "region": "litchfield"}),
    Object.freeze({"id": "hughes", "label": "Hughes", "region": "litchfield"}),
    Object.freeze({"id": "humpty_doo", "label": "Humpty Doo", "region": "litchfield"}),
    Object.freeze({"id": "jingili", "label": "Jingili", "region": "darwin"}),
    Object.freeze({"id": "johnston", "label": "Johnston", "region": "palmerston"}),
    Object.freeze({"id": "karama", "label": "Karama", "region": "darwin"}),
    Object.freeze({"id": "knuckey_lagoon", "label": "Knuckey Lagoon", "region": "litchfield"}),
    Object.freeze({"id": "koolpinyah", "label": "Koolpinyah", "region": "litchfield"}),
    Object.freeze({"id": "lambells_lagoon", "label": "Lambells Lagoon", "region": "litchfield"}),
    Object.freeze({"id": "larrakeyah", "label": "Larrakeyah", "region": "darwin", "aliases": Object.freeze(["Cullen Bay"])}),
    Object.freeze({"id": "leanyer", "label": "Leanyer", "region": "darwin"}),
    Object.freeze({"id": "lee_point", "label": "Lee Point", "region": "darwin"}),
    Object.freeze({"id": "livingstone", "label": "Livingstone", "region": "litchfield"}),
    Object.freeze({"id": "lloyd_creek", "label": "Lloyd Creek", "region": "litchfield"}),
    Object.freeze({"id": "ludmilla", "label": "Ludmilla", "region": "darwin"}),
    Object.freeze({"id": "lyons", "label": "Lyons", "region": "darwin"}),
    Object.freeze({"id": "malak", "label": "Malak", "region": "darwin"}),
    Object.freeze({"id": "manton", "label": "Manton", "region": "litchfield"}),
    Object.freeze({"id": "marlow_lagoon", "label": "Marlow Lagoon", "region": "palmerston"}),
    Object.freeze({"id": "marrara", "label": "Marrara", "region": "darwin"}),
    Object.freeze({"id": "mcminns_lagoon", "label": "McMinns Lagoon", "region": "litchfield"}),
    Object.freeze({"id": "micket_creek", "label": "Micket Creek", "region": "litchfield"}),
    Object.freeze({"id": "middle_point", "label": "Middle Point", "region": "litchfield"}),
    Object.freeze({"id": "millner", "label": "Millner", "region": "darwin"}),
    Object.freeze({"id": "mitchell", "label": "Mitchell", "region": "palmerston"}),
    Object.freeze({"id": "moil", "label": "Moil", "region": "darwin"}),
    Object.freeze({"id": "moulden", "label": "Moulden", "region": "palmerston"}),
    Object.freeze({"id": "muirhead", "label": "Muirhead", "region": "darwin"}),
    Object.freeze({"id": "murrumujuk", "label": "Murrumujuk", "region": "litchfield"}),
    Object.freeze({"id": "nakara", "label": "Nakara", "region": "darwin"}),
    Object.freeze({"id": "nightcliff", "label": "Nightcliff", "region": "darwin"}),
    Object.freeze({"id": "noonamah", "label": "Noonamah", "region": "litchfield"}),
    Object.freeze({"id": "palmerston_city", "label": "Palmerston City", "region": "palmerston"}),
    Object.freeze({"id": "parap", "label": "Parap", "region": "darwin"}),
    Object.freeze({"id": "pinelands", "label": "Pinelands", "region": "palmerston"}),
    Object.freeze({"id": "rapid_creek", "label": "Rapid Creek", "region": "darwin"}),
    Object.freeze({"id": "rosebery", "label": "Rosebery", "region": "palmerston"}),
    Object.freeze({"id": "shoal_bay", "label": "Shoal Bay", "region": "litchfield"}),
    Object.freeze({"id": "southport", "label": "Southport", "region": "litchfield"}),
    Object.freeze({"id": "stuart_park", "label": "Stuart Park", "region": "darwin"}),
    Object.freeze({"id": "the_gardens", "label": "The Gardens", "region": "darwin"}),
    Object.freeze({"id": "the_narrows", "label": "The Narrows", "region": "darwin"}),
    Object.freeze({"id": "tivendale", "label": "Tivendale", "region": "palmerston"}),
    Object.freeze({"id": "tiwi", "label": "Tiwi", "region": "darwin"}),
    Object.freeze({"id": "tumbling_waters", "label": "Tumbling Waters", "region": "litchfield"}),
    Object.freeze({"id": "virginia", "label": "Virginia", "region": "litchfield"}),
    Object.freeze({"id": "wagaman", "label": "Wagaman", "region": "darwin"}),
    Object.freeze({"id": "wak_wak", "label": "Wak Wak", "region": "litchfield"}),
    Object.freeze({"id": "wanguri", "label": "Wanguri", "region": "darwin"}),
    Object.freeze({"id": "weddell", "label": "Weddell", "region": "litchfield"}),
    Object.freeze({"id": "wickham", "label": "Wickham", "region": "litchfield"}),
    Object.freeze({"id": "winnellie", "label": "Winnellie", "region": "darwin"}),
    Object.freeze({"id": "wishart", "label": "Wishart", "region": "palmerston"}),
    Object.freeze({"id": "woodroffe", "label": "Woodroffe", "region": "palmerston"}),
    Object.freeze({"id": "woolner", "label": "Woolner", "region": "darwin"}),
    Object.freeze({"id": "wulagi", "label": "Wulagi", "region": "darwin"}),
    Object.freeze({"id": "yarrawonga", "label": "Yarrawonga", "region": "palmerston"}),
    Object.freeze({"id": "zuccoli", "label": "Zuccoli", "region": "palmerston"}),
  ]),
  sources: Object.freeze([
    Object.freeze({"url": "https://discover.darwin.nt.gov.au/blogs/moving-darwin-suburb-guide", "title": "City of Darwin, Moving to Darwin: Suburb Guide (Cullen Bay and CBD aliases)"}),
    Object.freeze({"url": "https://haveyoursay.nt.gov.au/city-of-palmerston-council-boundary/widgets/336443/faqs", "title": "NT Government, Palmerston boundary review FAQs (Northcrest within Berrimah)"}),
    Object.freeze({"url": "https://jointheterritory.nt.gov.au/__data/assets/pdf_file/0004/1328953/Greater_Darwin_regional_guide.pdf", "title": "NT Government, Greater Darwin Regional Guide, page 15 (suburb and locality lists)"}),
    Object.freeze({"url": "https://budget.nt.gov.au/regional-overview/greater-darwin", "title": "NT Budget 2026, Greater Darwin (regional scope)"}),
    Object.freeze({"url": "https://palmerston.nt.gov.au/your-community/major-projects/municipal-boundary-review", "title": "City of Palmerston, Municipal Boundary Review (completed expansion from 1 July 2022)"}),
    Object.freeze({"url": "https://ntec.nt.gov.au/electoral-boundaries/local-government-areas", "title": "NT Electoral Commission, Local government areas (maps and Greater Darwin unincorporated areas)"}),
    Object.freeze({"url": "https://www.defence.gov.au/adf-members-families/health-wellbeing/garrison-health-centres", "title": "Department of Defence, Garrison Health Centres (Robertson Barracks address in Holtze)"}),
    Object.freeze({"url": "https://www.ntlis.nt.gov.au/placenames/view.jsp?id=2039", "title": "NT Place Names Register, Freds Pass (registered spelling)"}),
  ])
});
