import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createSurveyModel, pairKey, characterCount, textWithinLimit, normaliseNewlines, toggleChoice} from './logic-core.mjs';
const spec=JSON.parse(readFileSync(new URL('./survey-spec.json',import.meta.url),'utf8'));
const base=JSON.parse(readFileSync(new URL('./baseline-fingerprints.json',import.meta.url),'utf8'));
const m=createSurveyModel(spec);
const cp=x=>structuredClone(x);
function state(cats=['I04']) {
  return {consent:'adult_agree',current_connection:'yes',presented_categories:cats,
    issues:Object.fromEntries(cats.map(c=>[c,{selected:[`${c}_01`]}])),needs:{},pairs:{}};
}
function needState(cats=['I04'],needs=['H01']) {
  const s=state(cats);
  for(const c of cats){s.needs[c]={selected:needs.slice()};for(const n of needs)s.pairs[pairKey(c,n)]={};}
  return s;
}
function setContacts(s,c,n,choices){s.pairs[pairKey(c,n)]||={};s.pairs[pairKey(c,n)].contacts=choices;return s;}
function noErrors(s){assert.deepEqual(m.validate(s),[]);}

test('retains all 20 categories and 170 original v3 substantive option labels and IDs',()=>{
  assert.equal(spec.issue_bank.length,20);assert.equal(spec.issue_bank.reduce((n,c)=>n+c.options.length,0),170);
  for(const c of spec.issue_bank)assert.deepEqual(Object.fromEntries(c.options.map(o=>[o.id,o.label])),base.substantive_items[c.id]);
});
test('retains all 100 locality records and aliases without additions',()=>assert.deepEqual(spec.geography.localities,base.locality_records));
test('all original eight needs remain selectable and H11 does not replace one',()=>{
  for(let i=1;i<=8;i++)assert.ok(spec.needs.some(n=>n.id===`H${String(i).padStart(2,'0')}`));assert.ok(spec.needs.some(n=>n.id==='H11'));
});
test('all required text fields are absent and long-text limit is consistent',()=>{
  let count=0; const walk=x=>{if(!x||typeof x!=='object')return;if(x.type==='text'){count++;assert.equal(x.required,false);assert.equal(x.max_length,10000);}for(const y of Object.values(x))walk(y);};walk(spec.pages);assert.ok(count>=6);
});
test('requires affirmative consent before adult route',()=>assert.deepEqual(m.route({}),['welcome']));
test('under 18 exits into existing independent route',()=>assert.deepEqual(m.route({consent:'under_18'}),['welcome','existing_youth_route']));
test('decline is not completion',()=>assert.deepEqual(m.route({consent:'adult_decline'}),['welcome','exit']));
test('explicit No to local current-serving connection gets scope route',()=>assert.deepEqual(m.route({consent:'adult_agree',current_connection:'no'}),['welcome','about','out_of_scope']));
test('outside residents with a serving family connection remain eligible',()=>{const s=state();s.residence_area='outside';assert.ok(m.route(s).includes('issues'));});
test('unknown connection is never recoded as Yes',()=>{const s=state();s.current_connection='unsure';assert.equal(m.activeAnswerSnapshot(s).current_connection,'unsure');});
test('zero issue route has five screens and still allows final comments',()=>assert.deepEqual(m.route(state([])),['welcome','about','issues','review','thanks']));
test('one category has one complete area page, no fragmented need pages',()=>{const s=needState(['I04'],['H01','H07']);assert.deepEqual(m.route(s),['welcome','about','issues','area:I04','review','thanks']);});
test('two categories and four needs have at most seven screens',()=>{const s=needState(['I04','I08'],['H01','H07']);assert.equal(m.activePairs(s).length,4);assert.equal(m.route(s).length,7);});
test('opening a category without selecting an issue does not report an issue',()=>{const s=state([]);s.presented_categories=['I04'];s.ui={openCategories:['I04']};assert.deepEqual(m.positiveCategories(s),[]);});
test('category Other without compulsory text can become priority',()=>{const s=state();s.issues.I04.selected=['I04_other'];assert.deepEqual(m.positiveCategories(s),['I04']);noErrors(s);});
test('positive no-detail control reports issue without guessing details',()=>{const s=state();s.issues.I04.selected=['I04_unspecified'];assert.deepEqual(m.positiveCategories(s),['I04']);noErrors(s);});
test('none, NA, refusal and unknown are not positive reports',()=>{for(const v of ['I04_none','I04_na','I04_prefer_not']){const s=state();s.issues.I04.selected=[v];assert.equal(m.positiveCategories(s).length,0);}});
test('global Other Yes becomes OTHER even without text',()=>{const s=state([]);s.other_issues_status='yes';assert.deepEqual(m.priorityCategories(s),['OTHER']);noErrors(s);});
test('global Other No/unknown/refusal cannot create OTHER',()=>{for(const v of ['no','unsure','prefer_not']){const s=state([]);s.other_issues_status=v;assert.deepEqual(m.positiveCategories(s),[]);}});
test('more than two categories requires selection or explicit skip, not arbitrary first two',()=>{const s=state(['I01','I04','I08']);assert.deepEqual(m.priorityCategories(s),[]);assert.ok(m.validateBeforeContinue(s,'issues').some(e=>e.path==='priority_categories'));});
test('one of three categories is an allowed priority choice',()=>{const s=state(['I01','I04','I08']);s.priority_categories=['I08'];assert.deepEqual(m.priorityCategories(s),['I08']);assert.deepEqual(m.validateBeforeContinue(s,'issues'),[]);});
test('over-selected priority categories are rejected, not truncated',()=>{const s=state(['I01','I04','I08']);s.priority_categories=['I01','I04','I08'];assert.deepEqual(m.priorityCategories(s),[]);assert.ok(m.validate(s).length);});
test('skipping detail preserves all reported issues and goes to final comments',()=>{const s=state(['I01','I04','I08']);s.skip_detail=true;assert.equal(m.route(s).length,5);assert.equal(Object.keys(m.activeAnswerSnapshot(s).issues).length,3);});
test('no help H10 creates no pair and keeps a category comment',()=>{const s=needState();s.needs.I04.selected=['H10'];delete s.pairs['I04::H01'];assert.deepEqual(m.activePairs(s),[]);assert.equal(m.areaView(s,'I04').fallbackComment,true);});
test('H11 unspecified positive need generates one genuine pair',()=>{const s=needState(['I04'],['H11']);assert.equal(m.activePairs(s)[0].need,'H11');noErrors(s);});
test('H11 is exclusive with concrete kinds of help',()=>{const s=needState(['I04'],['H01','H11']);assert.ok(m.validate(s).some(e=>e.path==='needs.I04.selected'));});
test('needs left blank are not no-help',()=>{const s=state();s.needs.I04={};assert.deepEqual(m.selectedNeeds(s,'I04'),[]);assert.notEqual(m.activeAnswerSnapshot(s).needs.I04.selected[0],'H10');});
test('more than two needs requires explicit priority/skip',()=>{const s=needState(['I04'],['H01','H05','H07']);s.pairs={};assert.deepEqual(m.priorityNeeds(s,'I04'),[]);assert.ok(m.validateBeforeContinue(s,'area:I04').some(e=>e.path==='needs.I04.priority'));});
test('selected lower-priority needs remain in analysis but not followed',()=>{const s=needState(['I04'],['H01','H05','H07']);s.needs.I04.priority=['H07'];s.pairs={'I04::H07':{}};const t=m.toAnalysisTables(s,'R1');assert.equal(t.needs.length,3);assert.equal(t.needs.filter(n=>n.tracked).length,1);});
test('same kind of help in two categories remains two distinct pairs',()=>{const s=needState(['I04','I08']);setContacts(s,'I04','H01',['N01']);setContacts(s,'I08','H01',['N04']);assert.deepEqual(m.ratingSources(s,'I04::H01'),['N01']);assert.deepEqual(m.ratingSources(s,'I08::H01'),['N04']);});
test('military-only contact never generates a military rating or characteristic',()=>{const s=setContacts(needState(),'I04','H01',['M_ALL']);assert.deepEqual(m.ratingSources(s,'I04::H01'),[]);assert.deepEqual(m.resourceSets(s,'I04').used,[]);assert.equal(m.areaView(s,'I04').outcomeBlocks.length,1);});
test('mixed contacts rate only nonmilitary/personal sources',()=>{const s=setContacts(needState(),'I04','H01',['M_ALL','N01','N06']);assert.deepEqual(m.ratingSources(s,'I04::H01'),['N01','N06']);});
test('explicit no contact is distinct from missing and still gets an outcome block',()=>{const s=setContacts(needState(),'I04','H01',['NO_CONTACT']);assert.equal(m.contactsComplete(s,'I04::H01'),true);assert.equal(m.areaView(s,'I04').outcomeBlocks.length,1);});
test('missing contacts do not become non-use',()=>{const s=needState();assert.equal(m.resourceSets(s,'I04').nonUseKnown,false);assert.deepEqual(m.resourceSets(s,'I04').notUsed,[]);});
test('unknown/refused contacts cannot establish non-use',()=>{for(const x of ['unsure','prefer_not']){const s=setContacts(needState(),'I04','H01',[x]);assert.equal(m.resourceSets(s,'I04').nonUseKnown,false);}});
test('Q32 is omitted if one need contact answer is missing, positive Q33 remains',()=>{const s=needState(['I04'],['H01','H07']);setContacts(s,'I04','H01',['N01']);assert.deepEqual(m.resourceSets(s,'I04').notUsed,[]);assert.deepEqual(m.resourceSets(s,'I04').used,['N01']);});
test('Q32/Q33 deduplicate a source across two needs in one category',()=>{const s=needState(['I04'],['H01','H07']);setContacts(s,'I04','H01',['N01']);setContacts(s,'I04','H07',['N01']);assert.deepEqual(m.resourceSets(s,'I04').used,['N01']);assert.ok(!m.resourceSets(s,'I04').notUsed.includes('N01'));});
test('same source used in one category and not another stays category-specific',()=>{const s=needState(['I04','I08']);setContacts(s,'I04','H01',['N01']);setContacts(s,'I08','H01',['NO_CONTACT']);assert.ok(m.resourceSets(s,'I04').used.includes('N01'));assert.ok(m.resourceSets(s,'I08').notUsed.includes('N01'));});
test('generic Other is never invented as an unused source',()=>{const s=setContacts(needState(),'I04','H01',['NO_CONTACT']);assert.ok(!m.resourceSets(s,'I04').notUsed.includes('N07'));});
test('networks displayed once on first relevant category',()=>{const s=needState(['I04','I08']);setContacts(s,'I04','H01',['N06']);setContacts(s,'I08','H01',['N06']);assert.equal(m.networkOwner(s),'I04');assert.equal(m.areaView(s,'I08').showPersonalNetworks,false);});
test('moving network owner preserves general network answer',()=>{const s=needState(['I04','I08']);setContacts(s,'I04','H01',['N06']);setContacts(s,'I08','H01',['N06']);s.personal_networks=['PN04'];const d=cp(s);d.pairs['I04::H01'].contacts=['NO_CONTACT'];const result=m.prepareUpdate(s,d);assert.equal(m.networkOwner(result.state),'I08');assert.deepEqual(result.state.personal_networks,['PN04']);});
test('last personal contact removal clears inapplicable network answers with confirmation',()=>{const s=setContacts(needState(),'I04','H01',['N06']);s.personal_networks=['PN04'];const d=cp(s);d.pairs['I04::H01'].contacts=['NO_CONTACT'];const r=m.prepareUpdate(s,d);assert.equal(r.state.personal_networks,undefined);assert.ok(r.removedPaths.includes('personal_networks'));});
test('no-help-received is an unscored value different from Not at all',()=>{const s=setContacts(needState(),'I04','H01',['N01']);s.pairs['I04::H01'].ratings={N01:'no_help_received'};noErrors(s);assert.ok(!spec.helpfulness_scale.some(o=>o.id==='no_help_received'));assert.notEqual('no_help_received','not_at_all');});
test('rating for wrong need or military source is invalid',()=>{const s=setContacts(needState(),'I04','H01',['M_ALL']);s.pairs['I04::H01'].ratings={M_ALL:'well',N01:'well'};assert.equal(m.validate(s).filter(e=>e.path.includes('ratings')).length,2);});
test('overall met need may still have a current gap without forced contradiction',()=>{const s=needState();s.pairs['I04::H01']={met_status:'all',current_gap:'yes'};noErrors(s);});
test('all rating non-score controls are valid and distinct',()=>{for(const v of ['no_help_received','too_soon','unsure','prefer_not']){const s=setContacts(needState(),'I04','H01',['N04']);s.pairs['I04::H01'].ratings={N04:v};noErrors(s);}});
test('blank counts stay unknown, explicit zero stays zero',()=>{const s=state();s.has_dependants='yes';s.dependants={counts:{under_2:{total:0,living_with:0}}};noErrors(s);assert.equal(m.dependantTotals(s).total,null);assert.equal(m.activeAnswerSnapshot(s).dependants.counts.under_2.total,0);});
test('full grid can be totalled without another count question',()=>{const s=state();s.has_dependants='yes';s.dependants={counts:Object.fromEntries(spec.pages[1].questions.find(q=>q.type==='dependants_grid').rows.map(r=>[r.id,{total:0,living_with:0}]))};s.dependants.counts['2_5']={total:2,living_with:1};assert.deepEqual(m.dependantTotals(s),{total:2,living_with:1,complete:true});});
test('negative, fractional and greater co-resident counts are invalid',()=>{for(const row of [{total:-1},{total:1.5},{total:1,living_with:2}]){const s=state();s.has_dependants='yes';s.dependants={counts:{under_2:row}};assert.ok(m.validate(s).length);}});
test('no dependants does not censor child or carer categories',()=>{const s=state(['I13','I14']);s.has_dependants='no';assert.deepEqual(m.positiveCategories(s),['I13','I14']);});
test('local area displays locality and local duration only',()=>{const s=state();s.residence_area='darwin';assert.deepEqual(m.visibleLocationFields(s),['residence_area','suburb','time_local']);});
test('outside residence never inherits serving member base as home',()=>{const s=state();s.residence_area='outside';s.past_residence='no';assert.deepEqual(m.visibleLocationFields(s),['residence_area','past_residence']);assert.equal(m.activeAnswerSnapshot(s).residence_area,'outside');});
test('same-screen initial area/locality/duration answers are retained',()=>{const before={consent:'adult_agree'},d={...state([]),residence_area:'darwin',suburb:'casuarina',time_local:'under3'};const r=m.prepareUpdate(before,d);assert.equal(r.state.suburb,'casuarina');assert.equal(r.state.time_local,'under3');});
test('changed area removes old mismatched locality but keeps substantive issues',()=>{const s=state();s.residence_area='darwin';s.suburb='casuarina';const d=cp(s);d.residence_area='palmerston';const r=m.prepareUpdate(s,d);assert.equal(r.state.suburb,undefined);assert.deepEqual(r.state.issues,s.issues);});
test('inline Other content is retained without mandatory text',()=>{const s=needState(['I04'],['H09']);setContacts(s,'I04','H09',['N07']);noErrors(s);assert.ok(m.activePairs(s).length);});
test('first-entry contact, outcome and comment answers survive reconciliation',()=>{const before=state(),d=needState();d.pairs['I04::H01']={contacts:['N01'],ratings:{N01:'well'},met_status:'some',comments:'An explanation'};const r=m.prepareUpdate(before,d);assert.deepEqual(r.state.pairs['I04::H01'],d.pairs['I04::H01']);});
test('first-entry characteristics are not mistaken for stale answers',()=>{const b=needState(),d=setContacts(cp(b),'I04','H01',['N01']);d.source_characteristics={I04:{used:{N01:['C03']},not_used:{N02:['C02']}}};assert.deepEqual(m.prepareUpdate(b,d).state.source_characteristics,d.source_characteristics);});
test('changing one category invalidates only its downstream data',()=>{const s=needState(['I04','I08']);s.pairs['I04::H01'].comments='old housing';s.pairs['I08::H01'].comments='health stays';const d=cp(s);d.issues.I04.selected=['I04_02'];const r=m.prepareUpdate(s,d);assert.equal(r.state.pairs['I04::H01'],undefined);assert.equal(r.state.pairs['I08::H01'].comments,'health stays');assert.ok(r.removedPaths.includes('pairs.I04::H01'));});
test('changing optional comments does not invalidate choices or ratings',()=>{const s=setContacts(needState(),'I04','H01',['N01']);s.pairs['I04::H01'].ratings={N01:'well'};const d=cp(s);d.pairs['I04::H01'].comments='new comment';const r=m.prepareUpdate(s,d);assert.deepEqual(r.state.pairs['I04::H01'].ratings,{N01:'well'});assert.deepEqual(r.removedPaths,[]);});
test('changing source keeps need-level narrative and overall outcome, flags review',()=>{const s=setContacts(needState(),'I04','H01',['N01']);s.pairs['I04::H01']={...s.pairs['I04::H01'],ratings:{N01:'well'},met_status:'some',comments:'Do not lose this'};const d=cp(s);d.pairs['I04::H01'].contacts=['N04'];const r=m.prepareUpdate(s,d);assert.equal(r.state.pairs['I04::H01'].comments,'Do not lose this');assert.equal(r.state.pairs['I04::H01'].met_status,'some');assert.deepEqual(r.state.pairs['I04::H01'].ratings,{});assert.ok(r.reviewCategories.includes('I04'));});
test('changing Other need meaning invalidates that pair only',()=>{const s=needState(['I04'],['H01','H09']);s.needs.I04.other_text='one';s.pairs['I04::H09'].comments='old';s.pairs['I04::H01'].comments='keep';const d=cp(s);d.needs.I04.other_text='two';const r=m.prepareUpdate(s,d);assert.equal(r.state.pairs['I04::H09'].comments,undefined);assert.equal(r.state.pairs['I04::H01'].comments,'keep');});
test('Remove area exposes destructive changes for confirmation',()=>{const s=state();const r=m.removeArea(s,'I04');assert.ok(r.removedPaths.includes('issues.I04'));assert.deepEqual(s.issues.I04.selected,['I04_01']);});
test('global no-issues reset exposes all removals and does not mutate original',()=>{const s=needState();s.pairs['I04::H01'].comments='keep until confirmed';const r=m.setOverallIssueControl(s,'none');assert.ok(r.removedPaths.includes('pairs.I04::H01'));assert.equal(s.pairs['I04::H01'].comments,'keep until confirmed');assert.deepEqual(m.positiveCategories(r.state),[]);});
test('snapshot excludes UI flags and inactive answer branches',()=>{const s=needState();s.ui={openCategories:['I04']};s.pairs['I08::H01']={comments:'orphan'};const snap=m.activeAnswerSnapshot(s);assert.equal(snap.ui,undefined);assert.equal(snap.pairs['I08::H01'],undefined);});
test('terminal ineligible states have no active snapshot',()=>{for(const consent of ['adult_decline','under_18'])assert.deepEqual(m.activeAnswerSnapshot({...needState(),consent}),{});assert.deepEqual(m.activeAnswerSnapshot({...needState(),current_connection:'no'}),{});});
test('10,000 ASCII characters accepted, 10,001 rejected without mutation',()=>{const s=needState();s.pairs['I04::H01'].comments='a'.repeat(10000);noErrors(s);s.pairs['I04::H01'].comments+='a';assert.ok(m.validate(s).some(e=>e.path.endsWith('.comments')));assert.equal(s.pairs['I04::H01'].comments.length,10001);});
test('10,000 emoji code points are accepted, not counted as 20,000 UTF-16 units',()=>{const value='😀'.repeat(10000);assert.equal(characterCount(value),10000);assert.equal(textWithinLimit(value),true);const s=needState();s.pairs['I04::H01'].comments=value;noErrors(s);assert.equal(m.activeAnswerSnapshot(s).pairs['I04::H01'].comments,value);});
test('newline count is normalised consistently and no user text is trimmed',()=>{assert.equal(normaliseNewlines(' a\r\nb\rc '),' a\nb\nc ');assert.equal(characterCount('a\r\nb'),3);const s=needState();s.pairs['I04::H01'].comments='  text\n';assert.equal(m.activeAnswerSnapshot(s).pairs['I04::H01'].comments,'  text\n');});
test('different needs keep independent 10,000-character comments',()=>{const s=needState(['I04'],['H01','H07']);s.pairs['I04::H01'].comments='A'.repeat(10000);s.pairs['I04::H07'].comments='B'.repeat(10000);noErrors(s);const t=m.toAnalysisTables(s,'R1');assert.equal(t.comments.filter(c=>c.scope==='need').length,2);});
test('optional text may be empty for every need and still finish',()=>{const s=needState();s.pairs['I04::H01'].comments='';assert.deepEqual(m.validateBeforeContinue(s,'review'),[]);assert.equal(m.route(s).at(-1),'thanks');});
test('checkbox none and refusal exclusivity works in both directions',()=>{assert.deepEqual(toggleChoice(['N01'],'NO_CONTACT',['NO_CONTACT']),['NO_CONTACT']);assert.deepEqual(toggleChoice(['NO_CONTACT'],'N01',['NO_CONTACT']),['N01']);});
test('review catches unfinished priorities rather than silently ending',()=>{const s=state(['I01','I04','I08']);assert.ok(m.validateBeforeContinue(s,'review').some(e=>e.path==='priority_categories'));});
test('unanswered specific issue link is not imputed to every checkbox',()=>{const s=needState();s.issues.I04.selected=['I04_01','I04_02'];const t=m.toAnalysisTables(s,'R1');assert.equal(t.needs[0].focus_scope,'category_only');assert.equal(t.needs[0].focus_issue_ids,null);});
test('explicit issue-to-need link is kept independently for each need',()=>{const s=needState(['I04'],['H01','H07']);s.issues.I04.selected=['I04_01','I04_02'];s.pairs['I04::H01'].focus_issues=['I04_01'];s.pairs['I04::H07'].focus_issues=['I04_02'];const t=m.toAnalysisTables(s,'R1');assert.deepEqual(t.needs[0].focus_issue_ids,['I04_01']);assert.deepEqual(t.needs[1].focus_issue_ids,['I04_02']);});
test('analysis includes no-help and unanswered need-area statuses',()=>{const s=state(['I04','I08']);s.needs.I04={selected:['H10']};const t=m.toAnalysisTables(s,'R1');assert.equal(t.need_areas.find(x=>x.category_id==='I04').response_status,'no_help_needed');assert.equal(t.need_areas.find(x=>x.category_id==='I08').response_status,'unanswered');});
test('analysis distinguishes category unopened versus viewed unanswered versus no issues',()=>{const s=state([]);s.presented_categories=['I04','I08'];s.issues.I08={selected:['I08_none']};const t=m.toAnalysisTables(s,'R1');assert.equal(t.categories.find(c=>c.category_id==='I01').status,'not_shown');assert.equal(t.categories.find(c=>c.category_id==='I04').status,'shown_unanswered');assert.equal(t.categories.find(c=>c.category_id==='I08').status,'none');});
test('analysis does not assign a military effectiveness value',()=>{const s=setContacts(needState(),'I04','H01',['M_ALL']);s.pairs['I04::H01'].met_status='some';const t=m.toAnalysisTables(s,'R1');assert.equal(t.sources[0].helpfulness_response,null);assert.equal(t.sources[0].measurement_scope,'source_flag_only');assert.equal(t.needs[0].met_status,'some');});
test('analysis keeps eligible unanswered feature rows for honest denominators',()=>{const s=setContacts(needState(),'I04','H01',['N01']);const t=m.toAnalysisTables(s,'R1');assert.equal(t.characteristics.length,5);assert.ok(t.characteristics.every(x=>x.response_status==='unanswered'));});
test('structured choices suffice without inventing a clinical resilience score',()=>{assert.equal(spec.local_adaptations.some(x=>x.includes('No new clinical resilience score')),true);assert.ok(!JSON.stringify(m.toAnalysisTables(needState(),'R1')).includes('resilience_score'));});
test('HTML-like comments remain data, not parsed markup',()=>{const s=needState();s.pairs['I04::H01'].comments='<img src=x onerror=alert(1)>';assert.equal(m.activeAnswerSnapshot(s).pairs['I04::H01'].comments,s.pairs['I04::H01'].comments);});

test('skip choices require booleans, not truthy strings',()=>{const s=state(['I01','I04','I08']);s.skip_detail='true';s.needs.I04={skip:'true'};assert.ok(m.validate(s).some(e=>e.path==='skip_detail'));assert.ok(m.validate(s).some(e=>e.path==='needs.I04.skip'));});
