import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import vm from 'node:vm';
import * as contact from '../contact-model.mjs';
const destination=resolve(process.argv[2]||'work/lc-it-handoff');mkdirSync(destination,{recursive:true});
const ctx=vm.createContext({structuredClone,URL,window:{scrollTo(){}},document:{querySelector(){return null;}}});
vm.runInContext(readFileSync(new URL('../geography.js',import.meta.url),'utf8'),ctx);
vm.runInContext(readFileSync(new URL('../young-children.js',import.meta.url),'utf8'),ctx);
const source=readFileSync(new URL('../survey.js',import.meta.url),'utf8');
vm.runInContext(source.slice(0,source.lastIndexOf("if (document.body.dataset.view === 'questions')"))+`
function bank(version){
 const sections=questionLibrarySections(version,'nt');
 const needOptions=[...DOMAINS[version],{id:'other_need',label:'Something else'}];
 const futureOptions=sections.find(s=>s.id==='future').fields.find(f=>f.key==='future_needs').options;
 const topicOptions=futureOptions.filter(x=>!['none','unsure','prefer'].includes(x.id));
 const focusOptions=[...needOptions,{id:'future_other_need',label:'A different future area'}];
 for(const section of sections)for(const item of section.fields){
  if(item.key==='future_priority')item.options=[...topicOptions,...item.options.filter(x=>['equal','unsure','prefer'].includes(x.id))];
  if(item.key==='focus_need')item.options=focusOptions;
  item.required=Boolean(item.required);
  if(item.type==='text')item.max_characters=maxTextLength(version);
  if(item.type==='short')item.max_characters=160;
 }
 return {version,recall_months:version==='adult'?12:3,sections,need_options:needOptions,future_topic_options:futureOptions,detail_repeat:version==='adult'?'One optional detail page per distinct recent or future topic, without a focus cap.':'One optional focus from the union of recent and future topics; retain all checked topics.',conditional_priority_options:'For adults, show future_priority after at least two substantive future topics. Filter topic choices to selected future_needs; retain equal/unsure/prefer alternatives.',topic_formats:'Record formats under areas[domain_id], never as a global answer.',shared_practical:'Show once for any substantive future topic. Enablers and practical note are optional; timing and in-person areas depend on selected formats.'};
}
globalThis.bank={schema_version:'lc-instrument-handoff/2',questionnaire_revision:'2026-09-28-topic-linked-support',survey_record_schema:'7.2',young_child_record_schema:'1.3',young_child_questionnaire_revision:'2026-09-27-area-priority',stage:'team_review_no_receiver',area_presentation:{primary:['darwin','palmerston','litchfield'],secondary_control:'Other area',secondary:['greater_darwin_other','outside','prefer'],all_optional:true},geography_precision:{area:'Broader area only; never infer a suburb.',suburb:'Named locality within the selected area.',other_locality:'Unlisted locality described within the selected area.',not_stated:'Area blank or not disclosed.'},analysis_unit:'submitted_response_perspective_not_unique_household',invitation:SURVEY_INVITATION,participant_notice:PARTICIPANT_INFORMATION,localities:GEOGRAPHY,forms:{adult:bank('adult'),youth:bank('youth')},routing:{current:'Choose residence_area first. Darwin, Palmerston, Litchfield/rural or Other Greater Darwin area -> full questionnaire even without a suburb.',not_disclosed:'Blank/prefer -> full questionnaire with residence unspecified.',outside:'Outside Greater Darwin + prior local residence Yes/Not sure/blank/prefer -> historical experience, kept separate.',no_local_experience:'Outside Greater Darwin + past_residence No -> scope explanation.',adf:'roles None -> scope explanation; current/former ADF relationships retained.',no_past_need:'Skip recent-experience detail only. Independently selected future topics, future_ideas and relevant practical questions remain available.'},operating_rules:{no_actual_receiver:true,no_survey_contact_join:true,keep_raw_text:true,no_silent_truncation:true,missing_not_no:true,technical_duplicate_handling:'Only remove verified duplicate submissions; preserve family members as separate perspectives.'}};
`,ctx);
const young=ctx.window.SURVEY_YOUNG_CHILDREN;
const youngSource=readFileSync(new URL('../young-children.js',import.meta.url),'utf8');
const constants=/const ADF_CONNECTIONS = Object\.freeze\((\[.*?\])\);[\s\S]*?const CHILD_STAGES = Object\.freeze\((\[.*?\])\);/.exec(youngSource);
const literal=text=>vm.runInNewContext('('+text+')');
ctx.bank.forms.young_child={version:'young_child_supported',record_schema:'1.3',perspectives:['child_expressions_recorded_by_parent_guardian','parent_guardian_observations'],required_background:{adf_connection:literal(constants[1])},optional_background:{residence_area:ctx.window.SURVEY_GEOGRAPHY.areas,suburb:'Optional native choice filtered by selected residence_area; plus other/prefer. Outside/prefer area hides the suburb question.',suburb_other:'Only for other within Greater Darwin.',child_stage:literal(constants[2])},questions:young.PROMPTS,guardian_observation:'What would you like to tell us about your child’s needs or support?',max_text_characters:young.MAX_LENGTH,participation:'Guardian permission required; child willingness controls child expressions only, not guardian observations.'};
ctx.bank.forms.interview_request={separate:true,notice_version:contact.CONTACT_NOTICE_VERSION,notice:contact.CONTACT_NOTICE,requesters:contact.CONTACT_REQUESTERS,age_bands:contact.CONTACT_AGES,contact_methods:contact.CONTACT_METHODS,interview_modes:contact.CONTACT_INTERVIEW_MODES,limits:contact.CONTACT_LIMITS,fields:Object.keys(contact.emptyRequest()),questions:[{id:'requester',label:'Who would be interviewed?',required:true,options:contact.CONTACT_REQUESTERS},{id:'age_band',label:'Your age group',required:true,options:contact.CONTACT_AGES,conditional:'Self requests only. Guardian requests automatically record minor (under 18).'},{id:'preferred_name',label:'Name / Your name',required:true,max_characters:80},{id:'phone',label:'Mobile number / Your mobile number',required:true,max_characters:30},{id:'email',label:'Email address',required:false,max_characters:contact.CONTACT_LIMITS.email},{id:'contact_method',label:'How should we arrange a time with you?',required:true,options:contact.CONTACT_METHODS},{id:'voicemail',label:'You may leave a voicemail saying Lutheran Care called.',required:false,conditional:'Only when contact_method=call; default false.'},{id:'contact_notes',label:'Any contact or access needs?',required:false,max_characters:contact.CONTACT_LIMITS.contact_notes},{id:'interview_mode',label:'How would you prefer to be interviewed?',required:false,options:contact.CONTACT_INTERVIEW_MODES},{id:'suggested_time',label:'Suggested interview date and time',required:false,max_characters:contact.CONTACT_LIMITS.suggested_time},{id:'topic',label:'What would you like to discuss? / What would your child like to discuss?',required:false,max_characters:600},{id:'guardian_authority',label:contact.CONTACT_GUARDIAN_DECLARATION,required:true,conditional:'Guardian requests only.'},{id:'consent',label:contact.CONTACT_CONSENT,required:true,variant_minor_self:contact.CONTACT_MINOR_CONSENT},{id:'capacity_acknowledged',label:contact.CONTACT_CAPACITY_ACKNOWLEDGEMENT,required:true}],consent:contact.CONTACT_CONSENT,minor_consent:contact.CONTACT_MINOR_CONSENT,guardian_authority:contact.CONTACT_GUARDIAN_DECLARATION,capacity_notice:contact.CONTACT_CAPACITY_NOTICE,routing:'Guardian supplies own contact details. A mobile number is required for all routes; optional valid email enables email scheduling. Age groups are Under 18 and 18 or older; guardian requests imply Under 18. Topic, interview format and suggested time are optional on all valid routes. Staff confirm appropriate participation arrangements before the interview. Scheduling is a brief exchange to agree time, not another interview. Voicemail only for calls, off by default. Collection/contact request IDs must never link to survey response IDs.'};
if(ctx.bank.forms.interview_request.questions.map(q=>q.id).sort().join('|')!==Object.keys(contact.emptyRequest()).sort().join('|'))throw new Error('Interview question dictionary needs synchronisation with current model fields.');
writeFileSync(resolve(destination,'question-bank.json'),JSON.stringify(ctx.bank,null,2)+'\n');
console.log('Exported platform-neutral question bank and all form routes to '+destination);
