import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import vm from 'node:vm';
import * as contact from '../contact-model.mjs';

const destination=resolve(process.argv[2]||'work/lc-it-handoff');
mkdirSync(destination,{recursive:true});
const ctx=vm.createContext({structuredClone,URL,window:{scrollTo(){}},document:{querySelector(){return null;}}});
vm.runInContext(readFileSync(new URL('../geography.js',import.meta.url),'utf8'),ctx);
vm.runInContext(readFileSync(new URL('../young-children.js',import.meta.url),'utf8'),ctx);
const source=readFileSync(new URL('../survey.js',import.meta.url),'utf8');
const end=source.lastIndexOf("if (document.body.dataset.view === 'questions')");
if(end<0)throw new Error('Survey bootstrap not found');
const injection=[
  "function bank(version){",
  " const sections=questionLibrarySections(version,'nt');",
  " for(const section of sections)for(const item of section.fields){",
  "  item.required=Boolean(item.required);",
  "  if(item.type==='text')item.max_characters=maxTextLength(version);",
  "  if(item.type==='short')item.max_characters=160;",
  " }",
  " return {version,recall_months:version==='adult'?12:3,problem_catalog:problemCatalog(version),help_types:version==='adult'?RAND_HELP_KINDS:YOUTH_HELP_KINDS,contact_sources:version==='adult'?RAND_CONTACT_SOURCES:YOUTH_CONTACT_SOURCES,seek_receipt_options:version==='adult'?RAND_SEEK_RECEIPT:null,source_outcome_options:version==='adult'?RAND_SOURCE_OUTCOMES:null,barrier_options:version==='adult'?RAND_BARRIERS:null,overall_met_options:version==='adult'?RAND_MET_STATUS:null,sections,problem_chain:{screen:'problem_screen',selection_key:'answers.problem_cues',other_text_key:'answers.problem_other',priority_step:'priority_pick',priority_key:'answers.priority_categories',max_detailed_categories:2,skip_detail_key:'answers.skip_detail_questions',area_step:'problem_detail:<category_id>',area_key:'answers.problem_details[category_id]',adult_area_fields:['focus_problems','help_kinds','other_help','priority_help','specific_need'],youth_area_fields:['story','needed_help','asked_anyone','anyone_helped','enough','remaining_need'],youth_enough_rule:'Show enough only when anyone_helped=yes; otherwise not asked, never default No.',adult_need_step:'need_chain:<category_id>:<need_id>',adult_need_key:'answers.problem_details[category_id].need_chains[need_id]',max_adult_need_chains:4,max_adult_priority_help_per_category:2,need_chain_fields:['specific_for_need','seek_receipt','sources','source_other','source_outcomes','barriers','barrier_note','bridge','met_status','current_gap','gap_detail'],source_outcome_key:'answers.problem_details[category_id].need_chains[need_id].source_outcomes[source_id]',overall_met_key:'answers.problem_details[category_id].need_chains[need_id].met_status',positive_future_step:'positive_future',interpretation:'A cue is a reported problem, not by itself a need or unmet need. For adults, at most two categories and two help kinds per category receive linked need chains; all original cue and help-kind selections remain recorded. Youth uses a shorter category-level path.'},supplement:{positive_support:'answers.positive_support',future_need:'answers.future_need',accounts:'answers.accounts',max_active_accounts:MAX_ACCOUNTS,role:'Supplemental open expression, not the main needs chain.'}};",
  "}",
  "globalThis.bank={schema_version:'lc-instrument-handoff/5',questionnaire_revision:'2026-09-29-rand-linked-needs',survey_record_schema:'9.0',young_child_record_schema:'1.3',young_child_questionnaire_revision:'2026-09-29-local-connection-preview',stage:'public_team_review_no_receiver',source:{credit:'Adult questionnaire adapted from Miller et al. (2011), RAND MG-1124, Appendix A.',title:'A New Approach for Assessing the Needs of Service Members and Their Families',authors:'Laura L. Miller et al.',publisher:'RAND Corporation',year:2011,appendix:'A',url:'https://www.rand.org/pubs/monographs/MG1124.html',adaptation:'Linked problem-needs-resource-outcome framework adapted with Greater Darwin wording; original US adult survey and local/youth versions are not equivalent or locally validated. No RAND endorsement is claimed.'},area_presentation:{primary:['darwin','palmerston','litchfield'],secondary_control:'Other area',secondary:['greater_darwin_other','outside','prefer'],all_optional:true},geography_precision:{area:'Broad area only; never infer a suburb.',suburb:'Named locality within the selected area.',other_locality:'Unlisted locality described within the selected area.',not_stated:'Area blank or not disclosed.'},analysis_unit:'submitted_response_perspective_not_unique_household',invitation:SURVEY_INVITATION,participant_notice_version:PARTICIPANT_NOTICE_VERSION,participant_notice:PARTICIPANT_INFORMATION,localities:GEOGRAPHY,forms:{adult:bank('adult'),youth:bank('youth')},routing:{current_connection_key:'answers.work_posting_greater_darwin',current:'Greater Darwin residence OR explicit current Greater Darwin work/posting connection -> full needs survey; keep residence and work/posting separate.',not_disclosed:'Blank/prefer residence -> full questionnaire with residence unspecified.',outside:'Outside Greater Darwin with no current work/posting connection and prior local residence Yes/Not sure/blank/prefer -> separate historical experience.',no_local_experience:'Outside Greater Darwin, no current work/posting connection, and past_residence No -> scope explanation.',adf:'roles None -> scope explanation; current/former ADF relationships retained.',problem_route:'Select concrete problem cues or explicit none/prefer; choose up to two selected categories for linked detail. No selected problem still reaches optional positive/future prompts.',supplement:'Additional open accounts are optional and capped at 100 active entries across the response.'},operating_rules:{no_actual_receiver:true,no_survey_contact_join:true,keep_raw_text:true,no_silent_truncation:true,missing_not_no:true,technical_duplicate_handling:'Only remove verified technical duplicates; preserve family members as separate perspectives.',distinct_units:'Response records, problem cues, detailed categories, help selections, category-by-need chains, contact sources, met-status answers and supplemental accounts have different denominators.'}};",
].join('\n');
vm.runInContext(source.slice(0,end)+injection,ctx);

const young=ctx.window.SURVEY_YOUNG_CHILDREN;
const youngSource=readFileSync(new URL('../young-children.js',import.meta.url),'utf8');
const constants=/const ADF_CONNECTIONS = Object\.freeze\((\[.*?\])\);[\s\S]*?const CHILD_STAGES = Object\.freeze\((\[.*?\])\);/.exec(youngSource);
const literal=text=>vm.runInNewContext('('+text+')');
ctx.bank.forms.young_child={version:'young_child_supported',record_schema:'1.3',questionnaire_revision:'2026-09-29-local-connection-preview',storage:'in_memory_preview_not_submitted',finish:'Finish preview; no response sent or saved.',scope:'Child may describe where they live or spend time with family, including when living elsewhere; optional residence remains a separate background field.',perspectives:['child_expressions_recorded_by_parent_guardian','parent_guardian_observations'],required_background:{adf_connection:literal(constants[1])},optional_background:{residence_area:ctx.window.SURVEY_GEOGRAPHY.areas,suburb:'Optional native choice filtered by selected residence_area; plus other/prefer. Outside/prefer area hides the suburb question.',suburb_other:'Only for other within Greater Darwin.',child_stage:literal(constants[2])},questions:young.PROMPTS,guardian_observation:'What would you like to tell us about your child’s needs or support?',max_text_characters:young.MAX_LENGTH,participation:'Guardian permission required; child willingness controls child expressions only, not guardian observations.'};
ctx.bank.forms.interview_request={separate:true,notice_version:contact.CONTACT_NOTICE_VERSION,notice:contact.CONTACT_NOTICE,requesters:contact.CONTACT_REQUESTERS,age_bands:contact.CONTACT_AGES,contact_methods:contact.CONTACT_METHODS,interview_modes:contact.CONTACT_INTERVIEW_MODES,limits:contact.CONTACT_LIMITS,fields:Object.keys(contact.emptyRequest()),questions:[{id:'requester',label:'Who would be interviewed?',required:true,options:contact.CONTACT_REQUESTERS},{id:'age_band',label:'Your age group',required:true,options:contact.CONTACT_AGES,conditional:'Self requests only. Guardian requests automatically record minor (under 18).'},{id:'preferred_name',label:'Name / Your name',required:true,max_characters:80},{id:'phone',label:'Mobile number / Your mobile number',required:true,max_characters:30},{id:'email',label:'Email address',required:false,max_characters:contact.CONTACT_LIMITS.email},{id:'contact_method',label:'How should we arrange a time with you?',required:true,options:contact.CONTACT_METHODS},{id:'voicemail',label:'You may leave a voicemail saying Lutheran Care called.',required:false,conditional:'Only when contact_method=call; default false.'},{id:'contact_notes',label:'Any contact or access needs?',required:false,max_characters:contact.CONTACT_LIMITS.contact_notes},{id:'interview_mode',label:'How would you prefer to be interviewed?',required:false,options:contact.CONTACT_INTERVIEW_MODES},{id:'suggested_time',label:'Suggested interview date and time',required:false,max_characters:contact.CONTACT_LIMITS.suggested_time},{id:'topic',label:'What would you like to discuss? / What would your child like to discuss?',required:false,max_characters:600},{id:'guardian_authority',label:contact.CONTACT_GUARDIAN_DECLARATION,required:true,conditional:'Guardian requests only.'},{id:'consent',label:contact.CONTACT_CONSENT,required:true,variant_minor_self:contact.CONTACT_MINOR_CONSENT},{id:'capacity_acknowledged',label:contact.CONTACT_CAPACITY_ACKNOWLEDGEMENT,required:true}],consent:contact.CONTACT_CONSENT,minor_consent:contact.CONTACT_MINOR_CONSENT,guardian_authority:contact.CONTACT_GUARDIAN_DECLARATION,capacity_notice:contact.CONTACT_CAPACITY_NOTICE,routing:'Guardian supplies own contact details. A mobile number is required for all routes; optional valid email enables email scheduling. Age groups are Under 18 and 18 or older; guardian requests imply Under 18. Topic, interview format and suggested time are optional on all valid routes. Staff confirm appropriate participation arrangements before the interview. Scheduling is a brief exchange to agree time, not another interview. Voicemail only for calls, off by default. Collection/contact request IDs must never link to survey response IDs.'};
if(ctx.bank.forms.interview_request.questions.map(q=>q.id).sort().join('|')!==Object.keys(contact.emptyRequest()).sort().join('|'))throw new Error('Interview question dictionary needs synchronisation with current model fields.');
writeFileSync(resolve(destination,'question-bank.json'),JSON.stringify(ctx.bank,null,2)+'\n');
console.log('Exported platform-neutral question bank and all form routes to '+destination);
